config/routes.rb
Rails.application.routes.draw do
  get "robots", to: "robots#robots_txt", as: :custom_robots_txt
  get "sitemap", to: "sitemap#index", as: :sitemap_xml, format: "xml"
  mount Cms::Engine => '/'

  match '/file_editor/(*path)', to: 'file_editor#index', via: [:get, :post], format: false, as: :file_editor
  match '/file_editor(*path)', to: 'file_editor#index', via: [:get, :post], format: false, as: :file



  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope "test", controller: "test" do
    get "video_iframe"
  end


  root as: "root_without_locale", to: "application#root_without_locale"

  scope ":locale", locale: /#{Cms.config.provided_locales.join("|")}/ do
    post "hire-us-request", to: "forms#hire_us_request", as: :hire_us_request
    post "join-us-request", to: "forms#join_us_request", as: :join_us_request

    resources :services, only: [:index, :show]

    scope :articles, controller: :articles do
      root as: :articles, action: :index
      get "filters/:filters", as: :articles_filters, action: :index_with_filters
      get ":id", as: :article, action: :show
    end

    scope "portfolio", controller: :portfolio do
      get ":id", action: :show, as: :portfolio_project
    end

    scope :projects, controller: "projects" do
      root action: :index, as: :projects
      get ":id", action: "show", as: :project_or_category
    end

    scope "blog", controller: "blog" do
      get "", action: "index", as: :blog
      get ":id", action: "show", as: "blog_article"
      get "/tags/:tags", action: "index", as: :article_tags
    end

    controller :pages do

      root action: "index"

      get "test", action: "test"


    end
  end

  scope "ajax", defaults: { ajax: true } do
    scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
      scope :projects, controller: "projects" do
        root action: :index, as: :ajax_projects
        get ":id", action: "show", as: :ajax_project_or_category
      end

      scope :articles, controller: :articles do
        get "filters/*filters", as: :ajax_articles_filters, action: :index_with_filters
      end
    end
  end






  locales = Cms.config.provided_locales

  if Cms::Page.table_exists?
    Cms::Page.all.each do |p|
      if !p.class.try(:disabled?)
        controller_name = "pages"

        locales.each do |locale|
          route_name = "#{locale}_#{p.page_key}"
          url = p.url(locale)
          #url = p.default_url if url.blank?
          #url = "/#{url}" if url.start_with?("/")

          get url , controller: controller_name, action: p.page_key, as: route_name, defaults: {locale: locale, page_id: p.id}
        end
      end
    end
  end

  match "*args", via: [:get, :post, :update, :delete, :create, :put], to: "application#render_not_found"
end

app/models/pages/services.rb
module Pages
  class Services < Page

  end
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible *attribute_names

  has_and_belongs_to_many :projects
  attr_accessible  :projects, :project_ids

  globalize :name, :descriptive_name, :url_fragment, :description, :long_description, :content, :portfolio_filter_name

  scope :published, -> { where(published: 't') }
  scope :sort_by_sorting_position, -> { order("sorting_position asc") }

  has_cache do
    pages :about_us, :articles, :contacts, :home, :projects, :services, :studio_life, Project.published, Article.published, Service.published

    Cms.config.provided_locales.each do |locale|
      pages "/ajax/#{locale}/projects/*"
    end
  end
  has_seo_tags
  has_sitemap_record
  has_navigation


  # attachents

  has_attached_file :icon
  has_attached_file :home_bg, styles: { xxl: "840x420#" }
  has_attached_file :list_image, styles: { xxl: "1024x850#", home_xxl: "840x420#", thumb: "100x100#" }

  [:icon, :home_bg, :list_image].each do |attachment_name|
    attr_accessible attachment_name
    allow_delete_attachment attachment_name
    do_not_validate_attachment_file_type attachment_name
  end


  def descriptive_name(locale = I18n.locale)
    t = self.translations_by_locale[locale]

    v = t.descriptive_name
    if v.blank?
      v = t.name
    end

    return v
  end

  def long_description(locale = I18n.locale)
    t = self.translations_by_locale[locale]

    v = t.long_description
    if v.blank?
      v = t.description
    end

    return v
  end

  def url(locale = I18n.locale)
    v = self.translations_by_locale[locale].url_fragment
    if !v.start_with?("/")
      v = "/#{v}"
    end

    "/#{locale}/services#{v}"
  end

  # def prev(relation = nil)
  #   Service.first
  # end
  #
  # def next(relation = nil)
  #   Service.prev
  # end

  def icon_path(style = :small)
    Rails.root.join("app/assets/images/svg/expertise-2/#{self.code_name}-#{style}.svg").to_s
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :initialize_services, only: [:index, :show]
  before_action :initialize_service, only: :show
  before_action :initialize_page_banner
  caches_page :index, :show
  def index

    set_page_metadata("services")
    @page_banner = {
        bg_image: 'banners/inner-page-main-banners-v1-expertise.jpg',
        title: t("services.index.banner.title"),
        numbers: [
          { number: "08", number_description: t("services.index.banner.fields-of-experise")}
        ],
        scroll_down_title: "view all"
    }

  end

  def show
    if @service
      set_page_metadata(@service)
      @page_banner = {
          bg_image: 'banners/inner-page-main-banners-v1-expertise.jpg',
          title: @service.name,
          numbers: [
              {number: "08", number_description: t("services.show.banner.cases")}
          ],
          scroll_down_title: "read more"
      }

      @related_projects = @service.projects.published
    end
  end

  private
  def initialize_services
    @services = Service.published.sort_by_sorting_position.includes(:translations)
  end

  def initialize_service
    @service = Service.published.joins(:translations).where(service_translations: { url_fragment: params[:id], locale: params[:locale] } ).first
  end

  def initialize_page_banner

  end
end

app/views/services/index.html.slim
.services
  - @services.each_with_index do |service, index|
    - service_url = service.try(:url)
    - service_icon_path = service.icon_path(:medium)
    - service_number = (index + 1).to_s
    - if service_number.length < 2
      - service_number = "0#{service_number}"
    - odd = index % 2 == 1
    - even = !odd
    - if even
      .service
        .service-info.go-left
          .inner
            a.svg-icon.service-icon href=service_url
              = embedded_svg_from_absolute_path(service_icon_path)
            a.service-name data-appear-top-offset="200" href=service_url
              = service.descriptive_name
            .service-description
              = service.long_description
            .item-links
              a.icon-link.play-link.read-more-link href=service_url
                = inline_svg("svg/play.svg")
                /= inline_svg("svg/play2.svg")
                span.icon-link-label
                  = t("read-more")
              a.icon-link.play-link href=project_or_category_path(id: service.translations_by_locale[I18n.locale].url_fragment)
                = inline_svg("svg/portfolio.svg")
                span.icon-link-label
                  = t("view-cases")
          .number
            = service_number
        a.service-image.go-right href=service_url
          .image style="background-image: url(#{service.list_image.url(:xxl)})"
    - else
      .service
        .service-info
          .inner
            a.svg-icon.service-icon href=service_url
              = embedded_svg_from_absolute_path(service_icon_path)
            a.service-name data-appear-top-offset="200" href=service_url
              = service.descriptive_name
            .service-description
              = service.long_description
            .item-links
              a.icon-link.play-link.read-more-link href=service_url
                = inline_svg("svg/play.svg")
                /= inline_svg("svg/play2.svg")
                span.icon-link-label
                  = t("read-more")
              a.icon-link.play-link href=project_or_category_path(id: service.translations_by_locale[I18n.locale].url_fragment)
                = inline_svg("svg/portfolio.svg")
                span.icon-link-label
                  = t("view-cases")
          .number
            = service_number
        a.service-image href=service_url
          .image style="background-image: url(#{service.list_image.url(:xxl)})"

app/views/services/show.html.slim
.light-bg
  .article-content.service-content
    = raw @service.content
  - if @related_projects.any?
    .related-projects-section
      .related-projects-title
        = inline_svg "svg/two-triangles.svg"
        p.related-projects-title-p
          = raw t("services.related-projects")
      .related-projects.projects
        .row.portfolio-projects
          - @related_projects.each do |project|
            = render "project", project: project, avatar_style: :projects_list

= render "bottom_navigation", prev_item: @service.prev(@services), next_item: @service.next(@services)