config/routes.rb
Rails.application.routes.draw do
  get "robots", to: "robots#robots_txt", as: :custom_robots_txt
  get "sitemap", to: "sitemap#index", as: :sitemap_xml, format: "xml"
  mount Cms::Engine => '/'

  match '/file_editor/(*path)', to: 'file_editor#index', via: [:get, :post], format: false, as: :file_editor
  match '/file_editor(*path)', to: 'file_editor#index', via: [:get, :post], format: false, as: :file



  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope "test", controller: "test" do
    get "video_iframe"
  end


  root as: "root_without_locale", to: "application#root_without_locale"

  scope ":locale", locale: /#{Cms.config.provided_locales.join("|")}/ do
    post "hire-us-request", to: "forms#hire_us_request", as: :hire_us_request
    post "join-us-request", to: "forms#join_us_request", as: :join_us_request

    resources :services, only: [:index, :show]

    scope :articles, controller: :articles do
      root as: :articles, action: :index
      get "filters/:filters", as: :articles_filters, action: :index_with_filters
      get ":id", as: :article, action: :show
    end

    scope "portfolio", controller: :portfolio do
      get ":id", action: :show, as: :portfolio_project
    end

    scope :projects, controller: "projects" do
      root action: :index, as: :projects
      get ":id", action: "show", as: :project_or_category
    end

    scope "blog", controller: "blog" do
      get "", action: "index", as: :blog
      get ":id", action: "show", as: "blog_article"
      get "/tags/:tags", action: "index", as: :article_tags
    end

    controller :pages do

      root action: "index"

      get "test", action: "test"


    end
  end

  scope "ajax", defaults: { ajax: true } do
    scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
      scope :projects, controller: "projects" do
        root action: :index, as: :ajax_projects
        get ":id", action: "show", as: :ajax_project_or_category
      end

      scope :articles, controller: :articles do
        get "filters/*filters", as: :ajax_articles_filters, action: :index_with_filters
      end
    end
  end






  locales = Cms.config.provided_locales

  if Cms::Page.table_exists?
    Cms::Page.all.each do |p|
      if !p.class.try(:disabled?)
        controller_name = "pages"

        locales.each do |locale|
          route_name = "#{locale}_#{p.page_key}"
          url = p.url(locale)
          #url = p.default_url if url.blank?
          #url = "/#{url}" if url.start_with?("/")

          get url , controller: controller_name, action: p.page_key, as: route_name, defaults: {locale: locale, page_id: p.id}
        end
      end
    end
  end

  match "*args", via: [:get, :post, :update, :delete, :create, :put], to: "application#render_not_found"
end

app/models/pages/projects.rb
module Pages
  class Projects < Page

  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible *attribute_names
  PROJECT_PARTS = {case: "#project-case", ux: "#ux-and-strategy", rwd: "#responsive-web-design", seo: ".project-seo-strategy", tech: "#technical-side"}

  has_and_belongs_to_many :services
  attr_accessible :services, :service_ids

  has_and_belongs_to_many :technologies
  attr_accessible :technologies, :technology_ids

  globalize :short_name, :name, :customer_name, :url_fragment, :site_url, :awards, :project_case, :logo_and_ci, :ux_and_strategy, :responsive_web_design, :technical_side_of_project, :seo_strategy

  boolean_scope :published
  scope :sort_by_sorting_position, -> { order("sorting_position asc") }

  boolean_scope :featured
  scope :sort_by_featured_position, -> { order("featured_position asc") }

  has_cache do
    pages :about_us, :articles, :contacts, :home, :projects, :services, :studio_life, Project.published, Article.published, Service.published
    Cms.config.provided_locales.each do |locale|
      pages "/ajax/#{locale}/projects/*"
    end
  end
  has_seo_tags
  has_sitemap_record
  has_navigation

  # attachments

  has_attached_file :home_banner_image, styles: {thumb: "400x400>"}

  has_attached_file :avatar, styles: { popup: "350x350#", projects_list: "510x510#", thumb: "100x100#" }
  has_attached_file :thumb, styles: { thumb: "100x100#" }
  has_attached_file :item_top_banner_bg_image, styles: {large: "1920x980", thumb: "400x400>"}
  has_attached_file :item_top_banner_image, styles: {thumb: "400x400>"}
  has_attached_file :vs_banner, styles: {thumb: "400x400>"}

  has_attached_file :item_bottom_banner_bg_image, styles: {large: "1920x980", thumb: "400x400>"}
  has_attached_file :item_bottom_banner_image, styles: {thumb: "400x400>"}



  has_attached_file :logo_and_ci_bg_image, styles: {thumb: "400x400>"}
  has_attached_file :ux_bg_image, styles: {thumb: "400x400>"}
  has_attached_file :rwd_bg_image, styles: {thumb: "400x400>"}
  has_attached_file :technical_side_of_project_bg_image, styles: {thumb: "400x400>"}

  [:avatar, :item_top_banner_bg_image, :item_top_banner_image, :vs_banner, :thumb, :item_bottom_banner_bg_image, :item_bottom_banner_image, :home_banner_image,
   :logo_and_ci_bg_image, :ux_bg_image, :rwd_bg_image, :technical_side_of_project_bg_image].each do |attachment_name|
    attr_accessible attachment_name
    allow_delete_attachment attachment_name
    do_not_validate_attachment_file_type attachment_name
  end

  has_images :logo_and_ci_images, styles: {thumb: "400x400>"}
  has_images :ux_images, styles: {thumb: "400x400>"}
  has_images :rwd_desktop_images, styles: {thumb: "400x400>", slide: "980x550#"}
  has_images :rwd_images, styles: {thumb: "400x400>"}



  def self.sass_option(name, default = nil, rails_admin_field_type = :string)
    opts = class_variable_get(:@@_sass_options) rescue []
    opts << {name: name, default: default, rails_admin_field_type: rails_admin_field_type}
    class_variable_set(:@@_sass_options, opts)
    field name
  end

  def self.sass_options
    class_variable_get(:@@_sass_options) rescue []
  end



  def sass_options(source = "ruby")
    #source = "db"
    opt_names = self.class.sass_options.map{|opt| opt[:name] }
    Hash[opt_names.map {|opt_name|
      puts "opt_name: #{opt_name}"
      if source == "db"
        val = self.send(opt_name)
      else
        val = specific_project_sass_options
        val = val[:options][opt_name.to_sym] if val && val[:options]
      end

      [opt_name, val]
    }.keep_if{|k, v| !v.blank? }]
  end

  def specific_project_sass_options
    if code_name == "arazzinni"
      colors = {
          black: "#212121",
          brown: "#876036",
          primary: "#876036"
      }

      options = {
          primary_color: colors[:brown],
          secondary_color: colors[:black],
          body_bg: "white",
          body_color: colors[:black],
          top_banner_title_color: colors[:black]
      }

      {options: options, colors: colors}
    elsif code_name == "10g-force"
      options = {
          :body_bg=>"#212121",
          :primary_color=>"rgb(89, 200, 230)",
          :secondary_color=>"rgb(255, 170, 44)",
          :third_color=>"rgb(239, 80, 35)",
          :button_lines_color=>"@third_color",
          :desktop_slider_background_color=>"@third_color",
          :technology_color=>"@secondary_color",
          :technology_name_color=>"white",
          :technology_svg_orbit_color=>"rgba(#fff, 0.2)",
          :project_bottom_banner_title_color=>"@third_color",
          :project_bottom_banner_description_color=>"#212121",
          :project_bottom_banner_buttons_color=>"#212121"
      }

      {options: options}
    end
  end

  sass_option :body_bg, "#212121"
  sass_option :primary_color, "red"
  sass_option :secondary_color, "blue"
  sass_option :third_color, "green"
  sass_option :body_color, "white"
  sass_option :link_hover_color, "@primary_color"
  sass_option :text_header_color, "@primary_color"
  sass_option :project_large_section_title_color, "rgba(128, 128, 128, 0.12)"
  sass_option :section_descriptive_title_color, "@primary_color"
  sass_option :button_lines_color, "@primary_color"
  sass_option :social_link_hover_bg_color, "@primary_color"


  sass_option :top_banner_title_color, "@primary_color"
  sass_option :top_banner_title_sup_color, "@primary_color"

  sass_option :top_banner_description_color, "@primary_color"
  #sass_option :project_case_section_bg_color, "none"
  #sass_option :project_case_header_color, "@text_header_color"
  #sass_option :project_case_text_color, "@body_color"
  sass_option :desktop_slider_background_color, "@primary_color"

  #sass_option :ux_and_strategy_section_bg_color, "none"
  #sass_option :ux_and_strategy_header_color, "@text_header_color"
  #sass_option :ux_and_strategy_text_color, "@body_color"






  #sass_option :seo_strategy_text_color, "@body_color"
  #sass_option :technical_side_of_project_text_color, "@body_color"
  sass_option :technology_color, "@primary_color"
  sass_option :technology_name_color, "@primary_color"
  sass_option :technology_svg_orbit_color, "@primary_color"

  sass_option :project_bottom_banner_title_color, "@primary_color"
  sass_option :project_bottom_banner_description_color, "@primary_color"
  sass_option :project_bottom_banner_buttons_color, "@primary_color"

  PROJECT_PARTS.each do |k, v|
    sass_option "#{k}_text_color".to_sym, "@body_color"
    sass_option "#{k}_header_color".to_sym, "@text_header_color"
    sass_option "#{k}_bg_color".to_sym, "inherit"
  end

  def self.project_css_mixin_options_string
    opts = sass_options
    opts.map{|opt|
      k = "$#{opt[:name].to_s}"
      has_default = opt.has_key?(:default) && opt[:default].present?
      if has_default
        default = opt[:default].gsub(/\A\@/, "$")

        "#{k}: #{default}"
      else
        k
      end


    }.join(", ")
  end

  def project_sass_options_string(source = "ruby")
    opts = sass_options(source)
    if opts.blank?
      return ""
    end

    opts.map{|k, v|
      if v.start_with?("@")
        v = opts[v.gsub(/\A\@/, "").to_sym]
      end
      "$#{k}: #{v}"
    }.join(", ")
  end

  def project_css
    opts_str = project_sass_options_string
    if opts_str.blank?
      return ""
    end

    indent = "  "


    files = ["calc_functions.sass", "detailed_css3_mixins.sass", "mixins.sass", "font_mixins.sass"]
    preloaded_sass = ""
    files.each do |f|
      preloaded_sass += File.read(Rails.root.join("app/assets/stylesheets/#{f}").to_s) + "\n"
    end

    ["theming_mixins.sass.erb"].each do |f|
      preloaded_sass += ERB.new(File.read(Rails.root.join("app/assets/stylesheets/#{f}").to_s) + "\n").result
    end

    if indent == "  "
      preloaded_sass = preloaded_sass.gsub("\t", "  ")
    end

    #mixin_src =


    body_str = "body.theme-#{code_name}"

    code = "\n#{body_str}\n#{indent}+theme(#{opts_str})"
    code += "\n#{indent}#{colors_code}"
    file_code = File.readlines(Rails.root.join("app/assets/stylesheets/themes/#{code_name}.sass"))
      .map{|s| indent + s }.join("")
    code += "\n" + file_code

    sass_code = "#{preloaded_sass}\n#{code}"
    puts "SASS code:"
    puts sass_code

    Sass.compile(sass_code, syntax: :sass, load_paths: [Rails.root.join("app/assets/stylesheets"), Rails.root.join("vendor/assets/bower_components")])
  end

  def colors_code(syntax = :sass, indent = "  ")
    colors = specific_project_sass_options
    colors = colors[:colors] if colors

    return "" if !colors || colors.blank?

    arr = colors.map{|k, v| "$#{k}_color: #{v}" }
    if syntax == :scss
      arr.join(";")
    else
      arr.join("\n#{indent}")
    end
  end

  def project_style
    css = project_css
    if css.blank?
      return ""
    end
    str = project_css.gsub("\n", "").gsub(/[ ]{0,}\{[ ]{0,}/, "{").gsub(": ", ":").gsub(/[ ]{0,}\}[ ]{0,}/, "}").gsub(";}", "}").gsub(/[ ]{0,},[ ]{0,}/, ",")
    "<style>#{str}</style>".html_safe
  end

  def url(locale = I18n.locale)
    if self.behance_url.present?
      return self.behance_url
    end
    v = self.translations_by_locale[locale].url_fragment
    if !v.start_with?("/")
      v = "/#{v}"
    end

    "/#{locale}/projects#{v}"
  end

  def self.load_data_defaults(associations = {})
    defaults = 4.times.map do |i|
      item_defaults = {}

      [:project_case, :logo_and_ci, :ux_and_strategy, :responsive_web_design, :technical_side_of_project, :seo_strategy].each do |column_name|
        I18n.available_locales.each do |locale|
          locale = locale.to_sym
          item_defaults[:translations] = {}
          item_defaults[:translations][locale] = {}
          item_defaults[:translations][locale][column_name.to_sym] = Fake.html(locale: locale)
        end

      end

      item_defaults
    end
  end

  def self.load_data(associations = {})
    defaults = self.load_data_defaults(associations)
    LoadData.load_resources(self, associations, defaults)

    self.all.each do |item|

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action
  before_action :set_project, only: [:show]
  caches_page :index, :show

  def index
    set_services
    set_projects_banner
    set_page_metadata("projects")
    initialize_projects
    #set_navigation_links(Project.first)
    if ajax?
      render "_projects.html", layout: false
    end

  end

  def show
    if @project
      #init_shuvar_info
      send("init_#{@project.code_name}") rescue nil
      set_page_metadata(@project)
      @theme = @project.code_name
      theme_template_path = "projects/templates/#{@theme}"
      #set_navigation_links(@project)
      initialize_projects

      if @project.is_a?(OldProject)
        @portfolio_item = @project.portfolio
        #render "old_project"
        @item = @project.portfolio
        render "old_item"
      elsif template_exists?(theme_template_path)
        render theme_template_path
      else
        render "show"
      end
    else
      set_category
      if @category
        set_services
        set_projects_banner
        set_page_metadata(@category)
        @projects = @category.projects.published
        if ajax?
          render "_projects.html", layout: false
        else
          render "index"
        end

      else
        render_not_found
      end
    end
  end

  protected

  def category

  end

  def set_services
    @services = Service.published.sort_by_sorting_position.joins(:projects).where(projects: { published: 't' }).uniq
    #@service = @services.first
  end

  def set_projects_banner
    last_created_at = @popup_projects.order("created_at desc").first.created_at
    days_last_added = 31

    @page_banner = {
        bg_image: 'banners/inner-page-main-banners-v1-portfolio.jpg',
        title: "Portfolio",
        numbers: [
            {number: @popup_projects.count, number_description: "projects"},
            {number: @services.count, number_description: "categories"},
            {number: days_last_added, number_description: "days last added"}
        ],
        scroll_down_title: "view all"
    }
  end

  def initialize_projects
    @projects = @popup_projects
    @old_projects = Portfolio.published
  end

  def set_category
    @category = Service.translation_class.where(url_fragment: params[:id], locale: I18n.locale).first.try{|t| Service.find(t.service_id) }
  end

  def set_project
    @project = Project.translation_class.where(url_fragment: params[:id], locale: I18n.locale).first.try{|t| Project.find(t.project_id) }
    if !@project
      return
    end
    project_translation = @project.translations_by_locale[I18n.locale]
    @project_banner = {
        title: project_translation.banner_title,
        title_sup: project_translation.banner_title_sup,
        short_description: project_translation.short_description,
        image_url: @project.item_top_banner_image.url,
    }

    @project_banner[:bg_image_url] = @project.item_top_banner_bg_image.url if @project.item_top_banner_bg_image.exists?
    #if respond_to?("init_#{@project.code_name}")
    #  send("init_#{@project.code_name}")
    #end

  end

  def set_navigation_links(project = @project)
    collection = @popup_projects
    # next_project = project.id
    # ids = @popup_projects.map(&:id)
    # current_index = ids.index(project.id)
    # prev_index = current_index - 1
    # next_index = current_index + 1
    # if prev_index < 0
    #   prev_index = ids.count - 1
    # end
    #
    # if next_index >= ids.count
    #   next_index = 0
    # end
    #
    # prev_id = ids[prev_index]
    # next_id = ids[next_index]
    #
    # prev_item = Project.find(prev_id)
    # next_item = Project.find(next_id)


    @prev, @next = [project.prev(collection), project.next(collection)].map{|item| {image: item.thumb.exists?(:thumb) ? item.thumb.url(:thumb) : item.avatar.url(:thumb), title: item.short_name, url: item.url } }
  end

  helper_method :template_exists?

  def render_partial(name, project_field = false, options = {} )

    if template_exists?("projects/#{@theme}/_#{name}")
      options = {partial: "projects/#{@theme}/#{name}"}.merge(options)
    elsif project_field == false || project_field.present?
      options = {partial: "#{name}"}.merge(options)
    else
      return ""
    end

    render_to_string(options)
  end

  helper_method :render_partial

  def init_shuvar_info
    @project_bottom_banner = {bg_image_url: "projects/shuvar_info/bottom_banner.jpg", asset_path: true}
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/old_portfolio/_developer_panel.html.erb
<div id="developers-panel">
  <div class="dev-pan f-height">
    <div class="mobile-column">
      <%  _description = project.description; I18n.available_locales.each {|locale|  break if _description.present?; _description = project.translations_by_locale[locale].description  }  %>
      <div class="dev-field project-description">
        <p><%= raw _description %></p>
      </div>

      <% if project.developers.any? %>
          <div class="dev-field">
            <h4><%= t("pages.portfolio-item.project_team") %></h4>
          </div>
          <!-- Developers and roles -->
          <% project.developers.each do |developer| %>
              <div class="dev-field">
                <p class="role"><%= developer.developer_role.name %></p>
                <p class="author"><%= developer.first_name+' '+developer.last_name %></p>
              </div>
          <% end %>
      <% end %>
    </div>


    <div class="mobile-column">
      <%  _thanks_to = project.thanks_to; I18n.available_locales.each {|locale|  break if _thanks_to.present?; _thanks_to = project.translations_by_locale[locale].thanks_to  }  %>
      <% if _thanks_to.present? %>
          <!-- Thanks for work -->
          <div class="dev-field">
            <h4 class="last-h4"><%= t("pages.portfolio-item.thanks_to") %></h4>
            <p class="author"><%= _thanks_to %></p>
          </div>
      <% end %>

      <% if project.thanks_image && project.thanks_image.exists?(:thumb) && project.thanks_image.exists?(:big)  %>
          <div style="padding-top:45px;"  class="dev-field thanks_image">
            <a href="<%=  project.thanks_image.url(:big) %>">
              <img class="thanks_image" src="<%= project.thanks_image.url(:thumb) %>" />
            </a>
          </div>
      <% end %>


      <% if project.portfolio_technologies.count > 0 %>
          <div class="dev-field technologies" style="padding-top:45px;">
            <ul>
              <% project.portfolio_technologies.each do |technology| %>
                  <li>
                    <a href="<%= technology.official_link %>">
                      <img src="<%= technology.avatar.url(:icon48) %>" />
                    </a>
                  </li>
              <% end %>
            </ul>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/old_portfolio/_portfolio_breadcrumbs.html.erb
<div id="breadcrumbs">
  <div class="container">
    <ul style="
    margin-left: 1%;
        padding-left: 0%;
    ">
      <li><a href="<%= root_path(locale: I18n.locale) %>"><%= t('partials.breadcrumbs.base.home-page') %></a></li>
      <li><a href="<%= portfolio_path(locale: I18n.locale) %>"><%= t('partials.breadcrumbs.portfolio-item.portfolio-list-page') %></a></li>
      <li><a href="<%= portfolio_category_path(category: @item.portfolio_category.slug, locale: I18n.locale) %>"><%= @item.portfolio_category.name %></a></li>
      <li><%= @item.name %></li>
    </ul>
  </div>
</div>

app/views/projects/old_portfolio/_portfolio_toolbar.html.erb
<div id="portfolio-toolbar" class="f-height">

  <a href="<%= @prev.url.present? %>" class="pt-left"></a>
  <a href="<%= portfolio_item_path(category: @next_portfolio.portfolio_category.slug, item: @next_portfolio.slug) %>" class="pt-right"></a>
  <% if @portfolio_item.result.present? || @portfolio_item.process.present? || @portfolio_item.live.present? %>
      <div class="container">
        <div class="tabs-wrapper">


          <section id="tabs-container" class="f-height">
            <% if _result   %>
                <div class="portfolio-tab bottom-arrow" id="result" >
                  <p><%= t("pages.portfolio-item.result") %></p>
                </div>
            <% end %>

            <% if @item.process && @item.process.length > 0  %>
                <div class="portfolio-tab bottom-arrow inactive-portfolio-tab" id="process" >
                  <p><%= t("pages.portfolio-item.process") %></p>
                </div>
            <% end %>

            <% if @item.live && @item.live.length > 0  %>
                <div class="portfolio-tab bottom-arrow inactive-portfolio-tab" id="live">
                  <p><%= t('pages.portfolio-item.live') %></p>
                </div>
            <% end %>
          </section>
        </div>
      </div>
  <% end %>
</div>

app/views/projects/old_portfolio/_portfolio_toolbar.html.slim
div id="portfolio-toolbar" class="f-height"
  - if @prev
    a href=@prev.url class="pt-left"
  - if @next
    a href=@next.url class="pt-right"

  - if @portfolio_item.result.present? || @portfolio_item.process.present? || @portfolio_item.live.present?
    .container
      .tabs-wrapper
        section id="tabs-container" class="f-height"
          - if @portfolio_item.result.present?
            div class="portfolio-tab bottom-arrow" id="result"
              p
                = t("pages.portfolio-item.result")
          - if